# Generated by Django 3.1.4 on 2021-02-06 14:27

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='cursos', verbose_name='Imagem'),
        ),
    ]
