# Generated by Django 3.1.4 on 2021-02-15 13:20

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210206_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='documento',
            field=models.FileField(default='', upload_to='CursosPDF', verbose_name='Documentação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='Cursos', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(verbose_name='Vagas'),
        ),
    ]
