# Generated by Django 3.1.4 on 2021-02-15 13:51

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210215_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='documento',
            field=models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Documentação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='cursos', verbose_name='Imagem'),
        ),
    ]
