# Generated by Django 3.1.4 on 2021-02-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210215_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='documento',
            field=models.FileField(default='', upload_to='cursopdf', verbose_name='Documentação'),
        ),
    ]
