# Generated by Django 3.1.4 on 2021-02-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210215_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='documento',
        ),
        migrations.AddField(
            model_name='curso',
            name='urldoc',
            field=models.URLField(default=False, verbose_name='Documentação'),
        ),
    ]
