# Generated by Django 3.1.4 on 2021-02-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210215_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='urldoc',
        ),
        migrations.AddField(
            model_name='curso',
            name='doc',
            field=models.FileField(default='', upload_to='cursospdf', verbose_name='Documentação'),
        ),
    ]
