from collections import Counter


# Counter
# =======
fernando_pessoa = '''
Não sou nada.
Nunca serei nada.
Não posso querer ser nada.
À parte isso, tenho em mim todos os sonhos do mundo.

Janelas do meu quarto,
Do meu quarto de um dos milhões do mundo que ninguém sabe quem é
(E se soubessem quem é, o que saberiam?),
Dais para o mistério de uma rua cruzada constantemente por gente,
Para uma rua inacessível a todos os pensamentos,
Real, impossivelmente real, certa, desconhecidamente certa,
Com o mistério das coisas por baixo das pedras e dos seres,
Com a morte a pôr umidade nas paredes e cabelos brancos nos homens,
Com o Destino a conduzir a carroça de tudo pela estrada de nada.

Estou hoje vencido, como se soubesse a verdade.
Estou hoje lúcido, como se estivesse para morrer,
E não tivesse mais irmandade com as coisas
Senão uma despedida, tornando-se esta casa e este lado da rua
A fileira de carruagens de um comboio, e uma partida apitada
De dentro da minha cabeça,
E uma sacudidela dos meus nervos e um ranger de ossos na ida.

Estou hoje perplexo, como quem pensou e achou e esqueceu.
Estou hoje dividido entre a lealdade que devo
À Tabacaria do outro lado da rua, como coisa real por fora,
E à sensação de que tudo é sonho, como coisa real por dentro.

Falhei em tudo.
Como não fiz propósito nenhum, talvez tudo fosse nada.
A aprendizagem que me deram,
Desci dela pela janela das traseiras da casa.
Fui até ao campo com grandes propósitos.
Mas lá encontrei só ervas e árvores,
E quando havia gente era igual à outra.
Saio da janela, sento-me numa cadeira. Em que hei de pensar?

Que sei eu do que serei, eu que não sei o que sou?
Ser o que penso? Mas penso tanta coisa!
E há tantos que pensam ser a mesma coisa que não pode haver tantos!
Gênio? Neste momento
Cem mil cérebros se concebem em sonho gênios como eu,
E a história não marcará, quem sabe?, nem um,
Nem haverá senão estrume de tantas conquistas futuras.
Não, não creio em mim.
Em todos os manicômios há doidos malucos com tantas certezas!
Eu, que não tenho nenhuma certeza, sou mais certo ou menos certo?
Não, nem em mim...
Em quantas mansardas e não-mansardas do mundo
Não estão nesta hora gênios-para-si-mesmos sonhando?
Quantas aspirações altas e nobres e lúcidas -
Sim, verdadeiramente altas e nobres e lúcidas -,
E quem sabe se realizáveis,
Nunca verão a luz do sol real nem acharão ouvidos de gente?
O mundo é para quem nasce para o conquistar
E não para quem sonha que pode conquistá-lo, ainda que tenha razão.
Tenho sonhado mais que o que Napoleão fez.
Tenho apertado ao peito hipotético mais humanidades do que Cristo,
Tenho feito filosofias em segredo que nenhum Kant escreveu.
Mas sou, e talvez serei sempre, o da mansarda,
Ainda que não more nela;
Serei sempre o que não nasceu para isso;
Serei sempre só o que tinha qualidades;
Serei sempre o que esperou que lhe abrissem a porta ao pé de uma parede sem porta,
E cantou a cantiga do Infinito numa capoeira,
E ouviu a voz de Deus num poço tapado.
Crer em mim? Não, nem em nada.
Derrame-me a Natureza sobre a cabeça ardente
O seu sol, a sua chuva, o vento que me acha o cabelo,
E o resto que venha se vier, ou tiver que vir, ou não venha.
Escravos cardíacos das estrelas,
Conquistámos todo o mundo antes de nos levantar da cama;
Mas acordamos e ele é opaco,
Levantamo-nos e ele é alheio,
Saímos de casa e ele é a terra inteira,
Mais o sistema solar e a Via Láctea e o Indefinido.

(Come chocolates, pequena;
Come chocolates!
Olha que não há mais metafísica no mundo senão chocolates.
Olha que as religiões todas não ensinam mais que a confeitaria.
Come, pequena suja, come!
Pudesse eu comer chocolates com a mesma verdade com que comes!
Mas eu penso e, ao tirar o papel de prata, que é de folha de estanho,
Deito tudo para o chão, como tenho deitado a vida.)

Mas ao menos fica da amargura do que nunca serei
A caligrafia rápida destes versos,
Pórtico partido para o Impossível.
Mas ao menos consagro a mim mesmo um desprezo sem lágrimas,
Nobre ao menos no gesto largo com que atiro
A roupa suja que sou, em rol, pra o decurso das coisas,
E fico em casa sem camisa.

(Tu, que consolas, que não existes e por isso consolas,
Ou deusa grega, concebida como estátua que fosse viva,
Ou patrícia romana, impossivelmente nobre e nefasta,
Ou princesa de trovadores, gentilíssima e colorida,
Ou marquesa do século dezoito, decotada e longínqua,
Ou cocote célebre do tempo dos nossos pais,
Ou não sei quê moderno - não concebo bem o quê -
Tudo isso, seja o que for, que sejas, se pode inspirar que inspire!
Meu coração é um balde despejado.
Como os que invocam espíritos invocam espíritos invoco
A mim mesmo e não encontro nada.
Chego à janela e vejo a rua com uma nitidez absoluta.
Vejo as lojas, vejo os passeios, vejo os carros que passam,
Vejo os entes vivos vestidos que se cruzam,
Vejo os cães que também existem,
E tudo isto me pesa como uma condenação ao degredo,
E tudo isto é estrangeiro, como tudo.)

Vivi, estudei, amei e até cri,
E hoje não há mendigo que eu não inveje só por não ser eu.
Olho a cada um os andrajos e as chagas e a mentira,
E penso: talvez nunca vivesses nem estudasses nem amasses nem cresses
(Porque é possível fazer a realidade de tudo isso sem fazer nada disso);
Talvez tenhas existido apenas, como um lagarto a quem cortam o rabo
E que é rabo para aquém do lagarto remexidamente

Fiz de mim o que não soube
E o que podia fazer de mim não o fiz.
O dominó que vesti era errado.
Conheceram-me logo por quem não era e não desmenti, e perdi-me.
Quando quis tirar a máscara,
Estava pegada à cara.
Quando a tirei e me vi ao espelho,
Já tinha envelhecido.
Estava bêbado, já não sabia vestir o dominó que não tinha tirado.
Deitei fora a máscara e dormi no vestiário
Como um cão tolerado pela gerência
Por ser inofensivo
E vou escrever esta história para provar que sou sublime.

Essência musical dos meus versos inúteis,
Quem me dera encontrar-me como coisa que eu fizesse,
E não ficasse sempre defronte da Tabacaria de defronte,
Calcando aos pés a consciência de estar existindo,
Como um tapete em que um bêbado tropeça
Ou um capacho que os ciganos roubaram e não valia nada.

Mas o Dono da Tabacaria chegou à porta e ficou à porta.
Olho-o com o desconforto da cabeça mal voltada
E com o desconforto da alma mal-entendendo.
Ele morrerá e eu morrerei.
Ele deixará a tabuleta, eu deixarei os versos.
A certa altura morrerá a tabuleta também, os versos também.
Depois de certa altura morrerá a rua onde esteve a tabuleta,
E a língua em que foram escritos os versos.
Morrerá depois o planeta girante em que tudo isto se deu.
Em outros satélites de outros sistemas qualquer coisa como gente
Continuará fazendo coisas como versos e vivendo por baixo de coisas como tabuletas,
Sempre uma coisa defronte da outra,
Sempre uma coisa tão inútil como a outra,
Sempre o impossível tão estúpido como o real,
Sempre o mistério do fundo tão certo como o sono de mistério da superfície,
Sempre isto ou sempre outra coisa ou nem uma coisa nem outra.

Mas um homem entrou na Tabacaria (para comprar tabaco?)
E a realidade plausível cai de repente em cima de mim.
Semiergo-me enérgico, convencido, humano,
E vou tencionar escrever estes versos em que digo o contrário.

Acendo um cigarro ao pensar em escrevê-los
E saboreio no cigarro a libertação de todos os pensamentos.
Sigo o fumo como uma rota própria,
E gozo, num momento sensitivo e competente,
A libertação de todas as especulações
E a consciência de que a metafísica é uma consequência de estar mal disposto.

Depois deito-me para trás na cadeira
E continuo fumando.
Enquanto o Destino mo conceder, continuarei fumando.

(Se eu casasse com a filha da minha lavadeira
Talvez fosse feliz.)
Visto isto, levanto-me da cadeira. Vou à janela.

O homem saiu da Tabacaria (metendo troco na algibeira das calças?).
Ah, conheço-o; é o Esteves sem metafísica.
(O Dono da Tabacaria chegou à porta.)
Como por um instinto divino o Esteves voltou-se e viu-me.
Acenou-me adeus, gritei-lhe Adeus ó Esteves!, e o universo
Reconstruiu-se-me sem ideal nem esperança, e o Dono da Tabacaria sorriu.
'''

# print(Counter(fernando_pessoa))
# Counter(
#     {
#         ' ': 1271,
#         'e': 836,
#         'a': 795,
#         'o': 718,
#         's': 512,
#         'r': 363,
#         'i': 337,
#         'm': 323,
#         'n': 322,
#         'u': 294,
#         't': 280,
#         'd': 271,
#         'c': 247,
#         '\n': 185,
#         'p': 134,
#         'l': 133,
#         ',': 122,
#         'v': 96,
#         'q': 92,
#         'h': 78,
#         '́': 69,
#         '.': 67,
#         '̃': 58,
#         'b': 58,
#         'g': 49,
#         'E': 48,
#         'f': 46,
#         'z': 30,
#         '-': 29,
#         'j': 24,
#         'C': 19,
#         '̧': 16,
#         'S': 16,
#         'O': 16,
#         'D': 15,
#         'A': 14,
#         'í': 14,
#         'T': 14,
#         'N': 13,
#         '?': 12,
#         'M': 12,
#         '̂': 11,
#         '̀': 10,
#         'x': 10,
#         '(': 8,
#         ')': 8,
#         '!': 8,
#         ';': 7,
#         'V': 7,
#         'é': 5,
#         'P': 5,
#         'Q': 5,
#         'F': 3,
#         'á': 3,
#         'I': 3,
#         'ú': 3,
#         'ê': 3,
#         'J': 2,
#         'R': 2,
#         'ó': 2,
#         'L': 2,
#         'ô': 1,
#         'G': 1,
#         'K': 1,
#         ':': 1
#     }
# )

fp_split = fernando_pessoa.split()
# print(Counter(fp_split))
Counter(
    {
        'que': 59,
        'o': 44,
        'a': 42,
        'e': 40,
        'de': 34,
        'E': 28,
        'não': 28,
        'como': 19,
        'da': 19,
        'em': 16,
        'os': 14,
        'do': 14,
        'um': 14,
        'é': 13,
        'uma': 13,
        'para': 11,
        'com': 10,
        'ao': 10,
        'nem': 10,
        'quem': 9,
        'se': 9,
        'por': 9,
        'coisa': 9,
        'Mas': 9,
        'eu': 9,
        'nada.': 8,
        'tudo': 8,
        'à': 8,
        'A': 7,
        'Tabacaria': 7,
        'Ou': 7,
        'das': 6,
        'mais': 6,
        'sem': 6,
        'mim': 5,
        'dos': 5,
        'mundo': 5,
        'rua': 5,
        'hoje': 5,
        'as': 5,
        'Como': 5,
        'me': 5,
        'ou': 5,
        'sempre': 5,
        'Sempre': 5,
        'ser': 4,
        'todos': 4,
        'mistério': 4,
        'coisas': 4,
        'Estou': 4,
        'na': 4,
        'Em': 4,
        'há': 4,
        'menos': 4,
        'O': 4,
        'no': 4,
        'isto': 4,
        'versos': 4,
        'Não': 3,
        'sou': 3,
        'serei': 3,
        'tenho': 3,
        'Com': 3,
        'pela': 3,
        'casa': 3,
        'real': 3,
        'talvez': 3,
        'fosse': 3,
        'só': 3,
        'era': 3,
        'sei': 3,
        'pode': 3,
        'Não,': 3,
        '-': 3,
        'Tenho': 3,
        'Serei': 3,
        'tinha': 3,
        'ele': 3,
        'vejo': 3,
        'Vejo': 3,
        'fazer': 3,
        'Dono': 3,
        'morrerá': 3,
        'tão': 3,
        'Nunca': 2,
        'À': 2,
        'isso,': 2,
        'meu': 2,
        'sabe': 2,
        'impossivelmente': 2,
        'real,': 2,
        'certa,': 2,
        'baixo': 2,
        'nos': 2,
        'Destino': 2,
        'esta': 2,
        'lado': 2,
        'minha': 2,
        'meus': 2,
        'janela': 2,
        'até': 2,
        'gente': 2,
        'outra.': 2,
        'numa': 2,
        'cadeira.': 2,
        'penso': 2,
        'mesma': 2,
        'momento': 2,
        'história': 2,
        'senão': 2,
        'tantas': 2,
        'mim.': 2,
        'certo': 2,
        'altas': 2,
        'nobres': 2,
        'lúcidas': 2,
        'sou,': 2,
        'porta': 2,
        'num': 2,
        'cabeça': 2,
        'Olha': 2,
        'metafísica': 2,
        'todas': 2,
        'tirar': 2,
        'nunca': 2,
        'mesmo': 2,
        'consolas,': 2,
        'isso': 2,
        'quê': 2,
        'invocam': 2,
        'espíritos': 2,
        'realidade': 2,
        'Talvez': 2,
        'lagarto': 2,
        'rabo': 2,
        'dominó': 2,
        'Quando': 2,
        'Estava': 2,
        'vou': 2,
        'escrever': 2,
        'defronte': 2,
        'consciência': 2,
        'estar': 2,
        'chegou': 2,
        'desconforto': 2,
        'mal': 2,
        'Ele': 2,
        'tabuleta,': 2,
        'versos.': 2,
        'certa': 2,
        'altura': 2,
        'Depois': 2,
        'outros': 2,
        'outra,': 2,
        'homem': 2,
        'cigarro': 2,
        'libertação': 2,
        'fumando.': 2,
        'Esteves': 2,
        'posso': 1,
        'querer': 1,
        'parte': 1,
        'sonhos': 1,
        'mundo.': 1,
        'Janelas': 1,
        'quarto,': 1,
        'Do': 1,
        'quarto': 1,
        'milhões': 1,
        'ninguém': 1,
        '(E': 1,
        'soubessem': 1,
        'é,': 1,
        'saberiam?),': 1,
        'Dais': 1,
        'cruzada': 1,
        'constantemente': 1,
        'gente,': 1,
        'Para': 1,
        'inacessível': 1,
        'pensamentos,': 1,
        'Real,': 1,
        'desconhecidamente': 1,
        'pedras': 1,
        'seres,': 1,
        'morte': 1,
        'pôr': 1,
        'umidade': 1,
        'nas': 1,
        'paredes': 1,
        'cabelos': 1,
        'brancos': 1,
        'homens,': 1,
        'conduzir': 1,
        'carroça': 1,
        'estrada': 1,
        'vencido,': 1,
        'soubesse': 1,
        'verdade.': 1,
        'lúcido,': 1,
        'estivesse': 1,
        'morrer,': 1,
        'tivesse': 1,
        'irmandade': 1,
        'Senão': 1,
        'despedida,': 1,
        'tornando-se': 1,
        'este': 1,
        'fileira': 1,
        'carruagens': 1,
        'comboio,': 1,
        'partida': 1,
        'apitada': 1,
        'De': 1,
        'dentro': 1,
        'cabeça,': 1,
        'sacudidela': 1,
        'nervos': 1,
        'ranger': 1,
        'ossos': 1,
        'ida.': 1,
        'perplexo,': 1,
        'pensou': 1,
        'achou': 1,
        'esqueceu.': 1,
        'dividido': 1,
        'entre': 1,
        'lealdade': 1,
        'devo': 1,
        'outro': 1,
        'rua,': 1,
        'fora,': 1,
        'sensação': 1,
        'sonho,': 1,
        'dentro.': 1,
        'Falhei': 1,
        'tudo.': 1,
        'fiz': 1,
        'propósito': 1,
        'nenhum,': 1,
        'aprendizagem': 1,
        'deram,': 1,
        'Desci': 1,
        'dela': 1,
        'traseiras': 1,
        'casa.': 1,
        'Fui': 1,
        'campo': 1,
        'grandes': 1,
        'propósitos.': 1,
        'lá': 1,
        'encontrei': 1,
        'ervas': 1,
        'árvores,': 1,
        'quando': 1,
        'havia': 1,
        'igual': 1,
        'Saio': 1,
        'janela,': 1,
        'sento-me': 1,
        'hei': 1,
        'pensar?': 1,
        'Que': 1,
        'serei,': 1,
        'sou?': 1,
        'Ser': 1,
        'penso?': 1,
        'tanta': 1,
        'coisa!': 1,
        'tantos': 1,
        'pensam': 1,
        'haver': 1,
        'tantos!': 1,
        'Gênio?': 1,
        'Neste': 1,
        'Cem': 1,
        'mil': 1,
        'cérebros': 1,
        'concebem': 1,
        'sonho': 1,
        'gênios': 1,
        'eu,': 1,
        'marcará,': 1,
        'sabe?,': 1,
        'um,': 1,
        'Nem': 1,
        'haverá': 1,
        'estrume': 1,
        'conquistas': 1,
        'futuras.': 1,
        'creio': 1,
        'manicômios': 1,
        'doidos': 1,
        'malucos': 1,
        'certezas!': 1,
        'Eu,': 1,
        'nenhuma': 1,
        'certeza,': 1,
        'certo?': 1,
        'mim...': 1,
        'quantas': 1,
        'mansardas': 1,
        'não-mansardas': 1,
        'estão': 1,
        'nesta': 1,
        'hora': 1,
        'gênios-para-si-mesmos': 1,
        'sonhando?': 1,
        'Quantas': 1,
        'aspirações': 1,
        'Sim,': 1,
        'verdadeiramente': 1,
        '-,': 1,
        'realizáveis,': 1,
        'verão': 1,
        'luz': 1,
        'sol': 1,
        'acharão': 1,
        'ouvidos': 1,
        'gente?': 1,
        'nasce': 1,
        'conquistar': 1,
        'sonha': 1,
        'conquistá-lo,': 1,
        'ainda': 1,
        'tenha': 1,
        'razão.': 1,
        'sonhado': 1,
        'Napoleão': 1,
        'fez.': 1,
        'apertado': 1,
        'peito': 1,
        'hipotético': 1,
        'humanidades': 1,
        'Cristo,': 1,
        'feito': 1,
        'filosofias': 1,
        'segredo': 1,
        'nenhum': 1,
        'Kant': 1,
        'escreveu.': 1,
        'sempre,': 1,
        'mansarda,': 1,
        'Ainda': 1,
        'more': 1,
        'nela;': 1,
        'nasceu': 1,
        'isso;': 1,
        'qualidades;': 1,
        'esperou': 1,
        'lhe': 1,
        'abrissem': 1,
        'pé': 1,
        'parede': 1,
        'porta,': 1,
        'cantou': 1,
        'cantiga': 1,
        'Infinito': 1,
        'capoeira,': 1,
        'ouviu': 1,
        'voz': 1,
        'Deus': 1,
        'poço': 1,
        'tapado.': 1,
        'Crer': 1,
        'mim?': 1,
        'Derrame-me': 1,
        'Natureza': 1,
        'sobre': 1,
        'ardente': 1,
        'seu': 1,
        'sol,': 1,
        'sua': 1,
        'chuva,': 1,
        'vento': 1,
        'acha': 1,
        'cabelo,': 1,
        'resto': 1,
        'venha': 1,
        'vier,': 1,
        'tiver': 1,
        'vir,': 1,
        'venha.': 1,
        'Escravos': 1,
        'cardíacos': 1,
        'estrelas,': 1,
        'Conquistámos': 1,
        'todo': 1,
        'antes': 1,
        'levantar': 1,
        'cama;': 1,
        'acordamos': 1,
        'opaco,': 1,
        'Levantamo-nos': 1,
        'alheio,': 1,
        'Saímos': 1,
        'terra': 1,
        'inteira,': 1,
        'Mais': 1,
        'sistema': 1,
        'solar': 1,
        'Via': 1,
        'Láctea': 1,
        'Indefinido.': 1,
        '(Come': 1,
        'chocolates,': 1,
        'pequena;': 1,
        'Come': 1,
        'chocolates!': 1,
        'chocolates.': 1,
        'religiões': 1,
        'ensinam': 1,
        'confeitaria.': 1,
        'Come,': 1,
        'pequena': 1,
        'suja,': 1,
        'come!': 1,
        'Pudesse': 1,
        'comer': 1,
        'chocolates': 1,
        'verdade': 1,
        'comes!': 1,
        'e,': 1,
        'papel': 1,
        'prata,': 1,
        'folha': 1,
        'estanho,': 1,
        'Deito': 1,
        'chão,': 1,
        'deitado': 1,
        'vida.)': 1,
        'fica': 1,
        'amargura': 1,
        'caligrafia': 1,
        'rápida': 1,
        'destes': 1,
        'versos,': 1,
        'Pórtico': 1,
        'partido': 1,
        'Impossível.': 1,
        'consagro': 1,
        'desprezo': 1,
        'lágrimas,': 1,
        'Nobre': 1,
        'gesto': 1,
        'largo': 1,
        'atiro': 1,
        'roupa': 1,
        'suja': 1,
        'rol,': 1,
        'pra': 1,
        'decurso': 1,
        'coisas,': 1,
        'fico': 1,
        'camisa.': 1,
        '(Tu,': 1,
        'existes': 1,
        'deusa': 1,
        'grega,': 1,
        'concebida': 1,
        'estátua': 1,
        'viva,': 1,
        'patrícia': 1,
        'romana,': 1,
        'nobre': 1,
        'nefasta,': 1,
        'princesa': 1,
        'trovadores,': 1,
        'gentilíssima': 1,
        'colorida,': 1,
        'marquesa': 1,
        'século': 1,
        'dezoito,': 1,
        'decotada': 1,
        'longínqua,': 1,
        'cocote': 1,
        'célebre': 1,
        'tempo': 1,
        'nossos': 1,
        'pais,': 1,
        'moderno': 1,
        'concebo': 1,
        'bem': 1,
        'Tudo': 1,
        'seja': 1,
        'for,': 1,
        'sejas,': 1,
        'inspirar': 1,
        'inspire!': 1,
        'Meu': 1,
        'coração': 1,
        'balde': 1,
        'despejado.': 1,
        'invoco': 1,
        'encontro': 1,
        'Chego': 1,
        'nitidez': 1,
        'absoluta.': 1,
        'lojas,': 1,
        'passeios,': 1,
        'carros': 1,
        'passam,': 1,
        'entes': 1,
        'vivos': 1,
        'vestidos': 1,
        'cruzam,': 1,
        'cães': 1,
        'também': 1,
        'existem,': 1,
        'pesa': 1,
        'condenação': 1,
        'degredo,': 1,
        'estrangeiro,': 1,
        'tudo.)': 1,
        'Vivi,': 1,
        'estudei,': 1,
        'amei': 1,
        'cri,': 1,
        'mendigo': 1,
        'inveje': 1,
        'eu.': 1,
        'Olho': 1,
        'cada': 1,
        'andrajos': 1,
        'chagas': 1,
        'mentira,': 1,
        'penso:': 1,
        'vivesses': 1,
        'estudasses': 1,
        'amasses': 1,
        'cresses': 1,
        '(Porque': 1,
        'possível': 1,
        'nada': 1,
        'disso);': 1,
        'tenhas': 1,
        'existido': 1,
        'apenas,': 1,
        'cortam': 1,
        'aquém': 1,
        'remexidamente': 1,
        'Fiz': 1,
        'soube': 1,
        'podia': 1,
        'fiz.': 1,
        'vesti': 1,
        'errado.': 1,
        'Conheceram-me': 1,
        'logo': 1,
        'desmenti,': 1,
        'perdi-me.': 1,
        'quis': 1,
        'máscara,': 1,
        'pegada': 1,
        'cara.': 1,
        'tirei': 1,
        'vi': 1,
        'espelho,': 1,
        'Já': 1,
        'envelhecido.': 1,
        'bêbado,': 1,
        'já': 1,
        'sabia': 1,
        'vestir': 1,
        'tirado.': 1,
        'Deitei': 1,
        'fora': 1,
        'máscara': 1,
        'dormi': 1,
        'vestiário': 1,
        'cão': 1,
        'tolerado': 1,
        'gerência': 1,
        'Por': 1,
        'inofensivo': 1,
        'provar': 1,
        'sublime.': 1,
        'Essência': 1,
        'musical': 1,
        'inúteis,': 1,
        'Quem': 1,
        'dera': 1,
        'encontrar-me': 1,
        'fizesse,': 1,
        'ficasse': 1,
        'defronte,': 1,
        'Calcando': 1,
        'aos': 1,
        'pés': 1,
        'existindo,': 1,
        'tapete': 1,
        'bêbado': 1,
        'tropeça': 1,
        'capacho': 1,
        'ciganos': 1,
        'roubaram': 1,
        'valia': 1,
        'ficou': 1,
        'porta.': 1,
        'Olho-o': 1,
        'voltada': 1,
        'alma': 1,
        'mal-entendendo.': 1,
        'morrerei.': 1,
        'deixará': 1,
        'deixarei': 1,
        'tabuleta': 1,
        'também,': 1,
        'também.': 1,
        'onde': 1,
        'esteve': 1,
        'língua': 1,
        'foram': 1,
        'escritos': 1,
        'Morrerá': 1,
        'depois': 1,
        'planeta': 1,
        'girante': 1,
        'deu.': 1,
        'satélites': 1,
        'sistemas': 1,
        'qualquer': 1,
        'Continuará': 1,
        'fazendo': 1,
        'vivendo': 1,
        'tabuletas,': 1,
        'inútil': 1,
        'impossível': 1,
        'estúpido': 1,
        'fundo': 1,
        'sono': 1,
        'superfície,': 1,
        'outra': 1,
        'entrou': 1,
        '(para': 1,
        'comprar': 1,
        'tabaco?)': 1,
        'plausível': 1,
        'cai': 1,
        'repente': 1,
        'cima': 1,
        'Semiergo-me': 1,
        'enérgico,': 1,
        'convencido,': 1,
        'humano,': 1,
        'tencionar': 1,
        'estes': 1,
        'digo': 1,
        'contrário.': 1,
        'Acendo': 1,
        'pensar': 1,
        'escrevê-los': 1,
        'saboreio': 1,
        'pensamentos.': 1,
        'Sigo': 1,
        'fumo': 1,
        'rota': 1,
        'própria,': 1,
        'gozo,': 1,
        'sensitivo': 1,
        'competente,': 1,
        'especulações': 1,
        'consequência': 1,
        'disposto.': 1,
        'deito-me': 1,
        'trás': 1,
        'cadeira': 1,
        'continuo': 1,
        'Enquanto': 1,
        'mo': 1,
        'conceder,': 1,
        'continuarei': 1,
        '(Se': 1,
        'casasse': 1,
        'filha': 1,
        'lavadeira': 1,
        'feliz.)': 1,
        'Visto': 1,
        'isto,': 1,
        'levanto-me': 1,
        'Vou': 1,
        'janela.': 1,
        'saiu': 1,
        '(metendo': 1,
        'troco': 1,
        'algibeira': 1,
        'calças?).': 1,
        'Ah,': 1,
        'conheço-o;': 1,
        'metafísica.': 1,
        '(O': 1,
        'porta.)': 1,
        'instinto': 1,
        'divino': 1,
        'voltou-se': 1,
        'viu-me.': 1,
        'Acenou-me': 1,
        'adeus,': 1,
        'gritei-lhe': 1,
        'Adeus': 1,
        'ó': 1,
        'Esteves!,': 1,
        'universo': 1,
        'Reconstruiu-se-me': 1,
        'ideal': 1,
        'esperança,': 1,
        'sorriu.': 1
    }
)

xpto = Counter(fp_split)
# print(xpto.most_common())
# [('que', 59), ('o', 44), ('a', 42), ('e', 40), ('de', 34), ('E', 28), ('não', 28), ('como', 19), ('da', 19),
#  ('em', 16), ('os', 14), ('do', 14), ('um', 14), ('é', 13), ('uma', 13), ('para', 11), ('com', 10), ('ao', 10),
#  ('nem', 10), ('quem', 9), ('se', 9), ('por', 9), ('coisa', 9), ('Mas', 9), ('eu', 9), ('nada.', 8), ('tudo', 8),
#  ('à', 8), ('A', 7), ('Tabacaria', 7), ('Ou', 7), ('das', 6), ('mais', 6), ('sem', 6), ('mim', 5), ('dos', 5),
#  ('mundo', 5), ('rua', 5), ('hoje', 5), ('as', 5), ('Como', 5), ('me', 5), ('ou', 5), ('sempre', 5), ('Sempre', 5),
#  ('ser', 4), ('todos', 4), ('mistério', 4), ('coisas', 4), ('Estou', 4), ('na', 4), ('Em', 4), ('há', 4),
#  ('menos', 4), ('O', 4), ('no', 4), ('isto', 4), ('versos', 4), ('Não', 3), ('sou', 3), ('serei', 3), ('tenho', 3),
#  ('Com', 3), ('pela', 3), ('casa', 3), ('real', 3), ('talvez', 3), ('fosse', 3), ('só', 3), ('era', 3), ('sei', 3),
#  ('pode', 3), ('Não,', 3), ('-', 3), ('Tenho', 3), ('Serei', 3), ('tinha', 3), ('ele', 3), ('vejo', 3),
#  ('Vejo', 3), ('fazer', 3), ('Dono', 3), ('morrerá', 3), ('tão', 3), ('Nunca', 2), ('À', 2), ('isso,', 2),
#  ('meu', 2), ('sabe', 2), ('impossivelmente', 2), ('real,', 2), ('certa,', 2), ('baixo', 2), ('nos', 2),
#  ('Destino', 2), ('esta', 2), ('lado', 2), ('minha', 2), ('meus', 2), ('janela', 2), ('até', 2), ('gente', 2),
#  ('outra.', 2), ('numa', 2), ('cadeira.', 2), ('penso', 2), ('mesma', 2), ('momento', 2), ('história', 2),
#  ('senão', 2), ('tantas', 2), ('mim.', 2), ('certo', 2), ('altas', 2), ('nobres', 2), ('lúcidas', 2), ('sou,', 2),
#  ('porta', 2), ('num', 2), ('cabeça', 2), ('Olha', 2), ('metafísica', 2), ('todas', 2), ('tirar', 2), ('nunca', 2),
#  ('mesmo', 2), ('consolas,', 2), ('isso', 2), ('quê', 2), ('invocam', 2), ('espíritos', 2), ('realidade', 2),
#  ('Talvez', 2), ('lagarto', 2), ('rabo', 2), ('dominó', 2), ('Quando', 2), ('Estava', 2), ('vou', 2),
#  ('escrever', 2), ('defronte', 2), ('consciência', 2), ('estar', 2), ('chegou', 2), ('desconforto', 2), ('mal', 2),
#  ('Ele', 2), ('tabuleta,', 2), ('versos.', 2), ('certa', 2), ('altura', 2), ('Depois', 2), ('outros', 2),
#  ('outra,', 2), ('homem', 2), ('cigarro', 2), ('libertação', 2), ('fumando.', 2), ('Esteves', 2), ('posso', 1),
#  ('querer', 1), ('parte', 1), ('sonhos', 1), ('mundo.', 1), ('Janelas', 1), ('quarto,', 1), ('Do', 1),
#  ('quarto', 1), ('milhões', 1), ('ninguém', 1), ('(E', 1), ('soubessem', 1), ('é,', 1), ('saberiam?),', 1),
#  ('Dais', 1), ('cruzada', 1), ('constantemente', 1), ('gente,', 1), ('Para', 1), ('inacessível', 1),
#  ('pensamentos,', 1), ('Real,', 1), ('desconhecidamente', 1), ('pedras', 1), ('seres,', 1), ('morte', 1),
#  ('pôr', 1), ('umidade', 1), ('nas', 1), ('paredes', 1), ('cabelos', 1), ('brancos', 1), ('homens,', 1),
#  ('conduzir', 1), ('carroça', 1), ('estrada', 1), ('vencido,', 1), ('soubesse', 1), ('verdade.', 1),
#  ('lúcido,', 1), ('estivesse', 1), ('morrer,', 1), ('tivesse', 1), ('irmandade', 1), ('Senão', 1),
#  ('despedida,', 1), ('tornando-se', 1), ('este', 1), ('fileira', 1), ('carruagens', 1), ('comboio,', 1),
#  ('partida', 1), ('apitada', 1), ('De', 1), ('dentro', 1), ('cabeça,', 1), ('sacudidela', 1), ('nervos', 1),
#  ('ranger', 1), ('ossos', 1), ('ida.', 1), ('perplexo,', 1), ('pensou', 1), ('achou', 1), ('esqueceu.', 1),
#  ('dividido', 1), ('entre', 1), ('lealdade', 1), ('devo', 1), ('outro', 1), ('rua,', 1), ('fora,', 1),
#  ('sensação', 1), ('sonho,', 1), ('dentro.', 1), ('Falhei', 1), ('tudo.', 1), ('fiz', 1), ('propósito', 1),
#  ('nenhum,', 1), ('aprendizagem', 1), ('deram,', 1), ('Desci', 1), ('dela', 1), ('traseiras', 1), ('casa.', 1),
#  ('Fui', 1), ('campo', 1), ('grandes', 1), ('propósitos.', 1), ('lá', 1), ('encontrei', 1), ('ervas', 1),
#  ('árvores,', 1), ('quando', 1), ('havia', 1), ('igual', 1), ('Saio', 1), ('janela,', 1), ('sento-me', 1),
#  ('hei', 1), ('pensar?', 1), ('Que', 1), ('serei,', 1), ('sou?', 1), ('Ser', 1), ('penso?', 1), ('tanta', 1),
#  ('coisa!', 1), ('tantos', 1), ('pensam', 1), ('haver', 1), ('tantos!', 1), ('Gênio?', 1), ('Neste', 1),
#  ('Cem', 1), ('mil', 1), ('cérebros', 1), ('concebem', 1), ('sonho', 1), ('gênios', 1), ('eu,', 1),
#  ('marcará,', 1), ('sabe?,', 1), ('um,', 1), ('Nem', 1), ('haverá', 1), ('estrume', 1), ('conquistas', 1),
#  ('futuras.', 1), ('creio', 1), ('manicômios', 1), ('doidos', 1), ('malucos', 1), ('certezas!', 1), ('Eu,', 1),
#  ('nenhuma', 1), ('certeza,', 1), ('certo?', 1), ('mim...', 1), ('quantas', 1), ('mansardas', 1),
#  ('não-mansardas', 1), ('estão', 1), ('nesta', 1), ('hora', 1), ('gênios-para-si-mesmos', 1), ('sonhando?', 1),
#  ('Quantas', 1), ('aspirações', 1), ('Sim,', 1), ('verdadeiramente', 1), ('-,', 1), ('realizáveis,', 1),
#  ('verão', 1), ('luz', 1), ('sol', 1), ('acharão', 1), ('ouvidos', 1), ('gente?', 1), ('nasce', 1),
#  ('conquistar', 1), ('sonha', 1), ('conquistá-lo,', 1), ('ainda', 1), ('tenha', 1), ('razão.', 1), ('sonhado', 1),
#  ('Napoleão', 1), ('fez.', 1), ('apertado', 1), ('peito', 1), ('hipotético', 1), ('humanidades', 1),
#  ('Cristo,', 1), ('feito', 1), ('filosofias', 1), ('segredo', 1), ('nenhum', 1), ('Kant', 1), ('escreveu.', 1),
#  ('sempre,', 1), ('mansarda,', 1), ('Ainda', 1), ('more', 1), ('nela;', 1), ('nasceu', 1), ('isso;', 1),
#  ('qualidades;', 1), ('esperou', 1), ('lhe', 1), ('abrissem', 1), ('pé', 1), ('parede', 1), ('porta,', 1),
#  ('cantou', 1), ('cantiga', 1), ('Infinito', 1), ('capoeira,', 1), ('ouviu', 1), ('voz', 1), ('Deus', 1),
#  ('poço', 1), ('tapado.', 1), ('Crer', 1), ('mim?', 1), ('Derrame-me', 1), ('Natureza', 1), ('sobre', 1),
#  ('ardente', 1), ('seu', 1), ('sol,', 1), ('sua', 1), ('chuva,', 1), ('vento', 1), ('acha', 1), ('cabelo,', 1),
#  ('resto', 1), ('venha', 1), ('vier,', 1), ('tiver', 1), ('vir,', 1), ('venha.', 1), ('Escravos', 1),
#  ('cardíacos', 1), ('estrelas,', 1), ('Conquistámos', 1), ('todo', 1), ('antes', 1), ('levantar', 1), ('cama;', 1),
#  ('acordamos', 1), ('opaco,', 1), ('Levantamo-nos', 1), ('alheio,', 1), ('Saímos', 1), ('terra', 1),
#  ('inteira,', 1), ('Mais', 1), ('sistema', 1), ('solar', 1), ('Via', 1), ('Láctea', 1), ('Indefinido.', 1),
#  ('(Come', 1), ('chocolates,', 1), ('pequena;', 1), ('Come', 1), ('chocolates!', 1), ('chocolates.', 1),
#  ('religiões', 1), ('ensinam', 1), ('confeitaria.', 1), ('Come,', 1), ('pequena', 1), ('suja,', 1), ('come!', 1),
#  ('Pudesse', 1), ('comer', 1), ('chocolates', 1), ('verdade', 1), ('comes!', 1), ('e,', 1), ('papel', 1),
#  ('prata,', 1), ('folha', 1), ('estanho,', 1), ('Deito', 1), ('chão,', 1), ('deitado', 1), ('vida.)', 1),
#  ('fica', 1), ('amargura', 1), ('caligrafia', 1), ('rápida', 1), ('destes', 1), ('versos,', 1), ('Pórtico', 1),
#  ('partido', 1), ('Impossível.', 1), ('consagro', 1), ('desprezo', 1), ('lágrimas,', 1), ('Nobre', 1),
#  ('gesto', 1), ('largo', 1), ('atiro', 1), ('roupa', 1), ('suja', 1), ('rol,', 1), ('pra', 1), ('decurso', 1),
#  ('coisas,', 1), ('fico', 1), ('camisa.', 1), ('(Tu,', 1), ('existes', 1), ('deusa', 1), ('grega,', 1),
#  ('concebida', 1), ('estátua', 1), ('viva,', 1), ('patrícia', 1), ('romana,', 1), ('nobre', 1), ('nefasta,', 1),
#  ('princesa', 1), ('trovadores,', 1), ('gentilíssima', 1), ('colorida,', 1), ('marquesa', 1), ('século', 1),
#  ('dezoito,', 1), ('decotada', 1), ('longínqua,', 1), ('cocote', 1), ('célebre', 1), ('tempo', 1), ('nossos', 1),
#  ('pais,', 1), ('moderno', 1), ('concebo', 1), ('bem', 1), ('Tudo', 1), ('seja', 1), ('for,', 1), ('sejas,', 1),
#  ('inspirar', 1), ('inspire!', 1), ('Meu', 1), ('coração', 1), ('balde', 1), ('despejado.', 1), ('invoco', 1),
#  ('encontro', 1), ('Chego', 1), ('nitidez', 1), ('absoluta.', 1), ('lojas,', 1), ('passeios,', 1), ('carros', 1),
#  ('passam,', 1), ('entes', 1), ('vivos', 1), ('vestidos', 1), ('cruzam,', 1), ('cães', 1), ('também', 1),
#  ('existem,', 1), ('pesa', 1), ('condenação', 1), ('degredo,', 1), ('estrangeiro,', 1), ('tudo.)', 1),
#  ('Vivi,', 1), ('estudei,', 1), ('amei', 1), ('cri,', 1), ('mendigo', 1), ('inveje', 1), ('eu.', 1), ('Olho', 1),
#  ('cada', 1), ('andrajos', 1), ('chagas', 1), ('mentira,', 1), ('penso:', 1), ('vivesses', 1), ('estudasses', 1),
#  ('amasses', 1), ('cresses', 1), ('(Porque', 1), ('possível', 1), ('nada', 1), ('disso);', 1), ('tenhas', 1),
#  ('existido', 1), ('apenas,', 1), ('cortam', 1), ('aquém', 1), ('remexidamente', 1), ('Fiz', 1), ('soube', 1),
#  ('podia', 1), ('fiz.', 1), ('vesti', 1), ('errado.', 1), ('Conheceram-me', 1), ('logo', 1), ('desmenti,', 1),
#  ('perdi-me.', 1), ('quis', 1), ('máscara,', 1), ('pegada', 1), ('cara.', 1), ('tirei', 1), ('vi', 1),
#  ('espelho,', 1), ('Já', 1), ('envelhecido.', 1), ('bêbado,', 1), ('já', 1), ('sabia', 1), ('vestir', 1),
#  ('tirado.', 1), ('Deitei', 1), ('fora', 1), ('máscara', 1), ('dormi', 1), ('vestiário', 1), ('cão', 1),
#  ('tolerado', 1), ('gerência', 1), ('Por', 1), ('inofensivo', 1), ('provar', 1), ('sublime.', 1), ('Essência', 1),
#  ('musical', 1), ('inúteis,', 1), ('Quem', 1), ('dera', 1), ('encontrar-me', 1), ('fizesse,', 1), ('ficasse', 1),
#  ('defronte,', 1), ('Calcando', 1), ('aos', 1), ('pés', 1), ('existindo,', 1), ('tapete', 1), ('bêbado', 1),
#  ('tropeça', 1), ('capacho', 1), ('ciganos', 1), ('roubaram', 1), ('valia', 1), ('ficou', 1), ('porta.', 1),
#  ('Olho-o', 1), ('voltada', 1), ('alma', 1), ('mal-entendendo.', 1), ('morrerei.', 1), ('deixará', 1),
#  ('deixarei', 1), ('tabuleta', 1), ('também,', 1), ('também.', 1), ('onde', 1), ('esteve', 1), ('língua', 1),
#  ('foram', 1), ('escritos', 1), ('Morrerá', 1), ('depois', 1), ('planeta', 1), ('girante', 1), ('deu.', 1),
#  ('satélites', 1), ('sistemas', 1), ('qualquer', 1), ('Continuará', 1), ('fazendo', 1), ('vivendo', 1),
#  ('tabuletas,', 1), ('inútil', 1), ('impossível', 1), ('estúpido', 1), ('fundo', 1), ('sono', 1),
#  ('superfície,', 1), ('outra', 1), ('entrou', 1), ('(para', 1), ('comprar', 1), ('tabaco?)', 1), ('plausível', 1),
#  ('cai', 1), ('repente', 1), ('cima', 1), ('Semiergo-me', 1), ('enérgico,', 1), ('convencido,', 1), ('humano,', 1),
#  ('tencionar', 1), ('estes', 1), ('digo', 1), ('contrário.', 1), ('Acendo', 1), ('pensar', 1), ('escrevê-los', 1),
#  ('saboreio', 1), ('pensamentos.', 1), ('Sigo', 1), ('fumo', 1), ('rota', 1), ('própria,', 1), ('gozo,', 1),
#  ('sensitivo', 1), ('competente,', 1), ('especulações', 1), ('consequência', 1), ('disposto.', 1),
#  ('deito-me', 1), ('trás', 1), ('cadeira', 1), ('continuo', 1), ('Enquanto', 1), ('mo', 1), ('conceder,', 1),
#  ('continuarei', 1), ('(Se', 1), ('casasse', 1), ('filha', 1), ('lavadeira', 1), ('feliz.)', 1), ('Visto', 1),
#  ('isto,', 1), ('levanto-me', 1), ('Vou', 1), ('janela.', 1), ('saiu', 1), ('(metendo', 1), ('troco', 1),
#  ('algibeira', 1), ('calças?).', 1), ('Ah,', 1), ('conheço-o;', 1), ('metafísica.', 1), ('(O', 1), ('porta.)', 1),
#  ('instinto', 1), ('divino', 1), ('voltou-se', 1), ('viu-me.', 1), ('Acenou-me', 1), ('adeus,', 1),
#  ('gritei-lhe', 1), ('Adeus', 1), ('ó', 1), ('Esteves!,', 1), ('universo', 1), ('Reconstruiu-se-me', 1),
#  ('ideal', 1), ('esperança,', 1), ('sorriu.', 1)]

# print(xpto.most_common(10))
# [('que', 59), ('o', 44), ('a', 42), ('e', 40), ('de', 34), ('E', 28), ('não', 28), ('como', 19), ('da', 19), ('em', 16)]

# print(xpto.most_common(3))
# [('que', 59), ('o', 44), ('a', 42)]

# print(Counter('abcc') & Counter('bcccd'))
# Counter({'c': 2, 'b': 1})

# print(set(['a', 'b', 'c']) & set(['b', 'c']))
# {'b', 'c'}